name: AI Article Review

on:
  push:
    branches:
      - main_disabled  # 一時的に無効化

jobs:
  review:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      issues: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 2 # 差分を取得するために直前のコミットまで取得

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: |
          npm ci || npm install
        timeout-minutes: 5

      - name: Get changed markdown files
        id: changed-files
        run: |
          FILES=$(git diff --name-only HEAD~1 HEAD | grep '^articles/.*\.md$' || echo "")
          echo "files=$FILES" >> $GITHUB_OUTPUT
          FILE_COUNT=$(echo "$FILES" | grep -c . || echo 0)
          echo "count=$FILE_COUNT" >> $GITHUB_OUTPUT
          if [ -z "$FILES" ]; then
            echo "No markdown files changed in articles/"
          else
            echo "Changed files count: $FILE_COUNT"
            echo "Changed files: $FILES"
          fi

      - name: OpenAI API Key Check
        if: steps.changed-files.outputs.files != ''
        run: |
          if [ -z "${{ secrets.OPENAI_API_KEY }}" ]; then
            echo "Warning: OPENAI_API_KEY is not set. AI review will be skipped."
            echo "skip_review=true" >> $GITHUB_ENV
          fi

      - name: Run AI review for each changed file
        if: steps.changed-files.outputs.files != '' && env.skip_review != 'true'
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_REPOSITORY: ${{ github.repository }}
        run: |
          set -e
          FILES="${{ steps.changed-files.outputs.files }}"
          COUNTER=0
          TOTAL_COUNT=${{ steps.changed-files.outputs.count }}
          
          for file in $FILES; do
            COUNTER=$((COUNTER + 1))
            echo "Reviewing: $file ($COUNTER/$TOTAL_COUNT)"
            
            # リトライロジックを追加
            RETRY_COUNT=0
            MAX_RETRIES=3
            SUCCESS=false
            
            while [ $RETRY_COUNT -lt $MAX_RETRIES ] && [ "$SUCCESS" = "false" ]; do
              if node scripts/ai-review.js "$file"; then
                SUCCESS=true
                echo "✅ Successfully reviewed: $file"
              else
                RETRY_COUNT=$((RETRY_COUNT + 1))
                if [ $RETRY_COUNT -lt $MAX_RETRIES ]; then
                  echo "⚠️ Review failed for $file, retrying ($RETRY_COUNT/$MAX_RETRIES)..."
                  sleep 5  # リトライ前に5秒待機
                else
                  echo "❌ Failed to review $file after $MAX_RETRIES attempts"
                fi
              fi
            done
            
            # API レート制限を避けるため、各レビュー間に待機
            # 多数のファイルの場合は待機時間を長くする
            if [ "$TOTAL_COUNT" -gt 10 ]; then
              echo "Waiting 10 seconds before next review (large batch)..."
              sleep 10
            else
              echo "Waiting 3 seconds before next review..."
              sleep 3
            fi
          done
          
          echo "✅ Completed reviewing $COUNTER files"
      
      - name: Review summary
        if: always()
        run: |
          if [ "${{ steps.changed-files.outputs.files }}" = "" ]; then
            echo "::notice::No article files were changed in this push"
          elif [ "${{ env.skip_review }}" = "true" ]; then
            echo "::warning::AI review was skipped due to missing OPENAI_API_KEY"
          else
            echo "::notice::AI review completed for ${{ steps.changed-files.outputs.count }} files"
          fi