name: AI Article Review

on:
  push:
    branches:
      - main

jobs:
  review:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      issues: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 2 # 差分を取得するために直前のコミットまで取得

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: |
          npm ci || npm install
        timeout-minutes: 5

      - name: Get changed markdown files
        id: changed-files
        run: |
          FILES=$(git diff --name-only HEAD~1 HEAD | grep '^articles/.*\.md$' || echo "")
          echo "files=$FILES" >> $GITHUB_OUTPUT
          FILE_COUNT=$(echo "$FILES" | grep -c . || echo 0)
          echo "count=$FILE_COUNT" >> $GITHUB_OUTPUT
          if [ -z "$FILES" ]; then
            echo "No markdown files changed in articles/"
          else
            echo "Changed files count: $FILE_COUNT"
            echo "Changed files: $FILES"
          fi

      - name: Check file count limit
        if: steps.changed-files.outputs.files != ''
        run: |
          FILE_COUNT=${{ steps.changed-files.outputs.count }}
          if [ "$FILE_COUNT" -gt 5 ]; then
            echo "::warning::Too many files changed ($FILE_COUNT). AI review will be limited to first 5 files to prevent API rate limits."
            echo "limit_review=true" >> $GITHUB_ENV
          fi

      - name: OpenAI API Key Check
        if: steps.changed-files.outputs.files != ''
        run: |
          if [ -z "${{ secrets.OPENAI_API_KEY }}" ]; then
            echo "Warning: OPENAI_API_KEY is not set. AI review will be skipped."
            echo "skip_review=true" >> $GITHUB_ENV
          fi

      - name: Run AI review for each changed file
        if: steps.changed-files.outputs.files != '' && env.skip_review != 'true'
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_REPOSITORY: ${{ github.repository }}
        run: |
          set -e
          FILES="${{ steps.changed-files.outputs.files }}"
          COUNTER=0
          MAX_FILES=5
          
          for file in $FILES; do
            if [ "$COUNTER" -ge "$MAX_FILES" ]; then
              echo "::notice::Reached review limit of $MAX_FILES files. Skipping remaining files."
              break
            fi
            
            echo "Reviewing: $file ($(($COUNTER + 1))/$MAX_FILES)"
            node scripts/ai-review.js "$file" || {
              echo "AI review failed for $file, continuing with next file..."
              continue
            }
            
            COUNTER=$((COUNTER + 1))
            # API レート制限を避けるため、各レビュー間に少し待機
            sleep 2
          done
      
      - name: Review summary
        if: always()
        run: |
          if [ "${{ steps.changed-files.outputs.files }}" = "" ]; then
            echo "::notice::No article files were changed in this push"
          elif [ "${{ env.skip_review }}" = "true" ]; then
            echo "::warning::AI review was skipped due to missing OPENAI_API_KEY"
          elif [ "${{ env.limit_review }}" = "true" ]; then
            echo "::warning::AI review was limited to 5 files due to large number of changes"
          else
            echo "::notice::AI review completed for changed files"
          fi