name: AI Article Review

on:
  push:
    branches:
      - main

jobs:
  review:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 2 # 差分を取得するために直前のコミットまで取得

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install openai

      - name: Get changed markdown files
        id: changed-files
        run: |
          FILES=$(git diff --name-only HEAD~1 HEAD | grep '^articles/.*\.md$' || echo "")
          echo "files=$FILES" >> $GITHUB_OUTPUT

      - name: Run AI review for each changed file
        if: steps.changed-files.outputs.files != ''
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_REPOSITORY: ${{ github.repository }}
        run: |
          for file in ${{ steps.changed-files.outputs.files }}; do
            node scripts/ai-review.js "$file"
          done
